# -*- coding: utf-8 -*-
"""aula-Variaveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EBHpxRts7ydaXOrb83jRjyPOkXkan4PW

## **NÚMEROS**
"""

preco = 47
quantidade = 0.250

total_apagar = quantidade * preco
print (total_apagar)



qte_itens_carrinho_compra = 0

qte_itens_carrinho_compra = qte_itens_carrinho_compra + 1 
print(qte_itens_carrinho_compra)

qte_itens_carrinho_compra = qte_itens_carrinho_compra + 1 
print(qte_itens_carrinho_compra)

a = 3
b = 2 

c = a/b
print(c)
print(type(c)) //divisão

d = a//b
print(d)
print(type(d)) //divisão inteira

print(int(3.9))
print(float(10))
print(complex(1))

svv_19 = 153.98
sqv_19 = 3

tkt_19 = svv_19 / sqv_19
print(tkt_19)

svv_20 = 337.01
sqv_20 = 7

tkt_20 = svv_20 / sqv_20
print(tkt_20)

svv_23 = 295.33
sqv_23 = 5

tkt_23 = svv_23 / sqv_23
print(tkt_23)

tkt = (tkt_19 + tkt_20 + tkt_23)/3
print(tkt)

"""## **STRING**"""

nome_aula = 'Aula 04, Modulo 01, String'

print(nome_aula)
print(type(nome_aula))

string_vazia = ""
print(string_vazia)
print(type(string_vazia))

nome = 'Andre Marcos'
sobrenome = 'Perez'

apresentacao = 'Olá meu nome é ' + nome +' ' + sobrenome + '.'
print(apresentacao)

nome = 'Andre Marcos'
sobrenome = 'Perez'

apresentacao = f'Olá meu nome é {nome} {sobrenome}.'
print(apresentacao)

email = 'andre.perez@gmail.com'
print('0: ' + email[0])
print('11: ' + email[11])

email = 'andre.perez@gmail.com'
email = email[0:11]
print(email)

endereco = 'Avenida Paulista, 1811, São Paulo, São Paulo, Brasil.'
#maiusculo: string.upper()
print(endereco.upper())

#posicao: string.find(substring)
posicao = endereco.find('Brasil')
print(posicao)

#substituicao: string.replace(antigo, novo)
print(endereco.replace('Avenida','Av'))

idade = 19
print(type(idade))

idade=str(idade)
print(type(idade))

#Sua empresa  
lat = ' -22.005320' 
lon = '-47.891040' 
 
#Startup adquirida 
latlon = ' -22.005320; -47.891040' 

posicao_char_divisao = latlon.find(';')
print(posicao_char_divisao)

lat_startup = latlon[0:posicao_char_divisao]
print(lat_startup)

lon_startup = latlon[posicao_char_divisao+1:len(latlon)]
print(lon_startup)

"""## **BOLEANOS**

# Nova seção
"""

verdadeiro = True
print(verdadeiro)

falso = False
print(falso)

saldo_em_conta = 200
valor_do_saque = 100

pode_efetuar_saque = valor_do_saque <= saldo_em_conta
print(pode_efetuar_saque)

codigo_de_seguranca = '852'
codigo_de_seguranca_Cadastro = '010'

pode_efetuar_pagamento = codigo_de_seguranca == codigo_de_seguranca_Cadastro
print(pode_efetuar_saque)

idade = 19
tipo_sangue = 'O-'
filhos = 0
telefone_fixo = None
telefone_fixo = ''

print(bool(idade))
print(bool(tipo_sangue))
print(bool(filhos))
print(bool(telefone_fixo))
print(bool(telefone_fixo))

usuario = 'andre.perez' 
senha = 'andre123' 

usuario_cadastro = 'andre.perez' 
senha_cadastro = 'andre321' 

usuario_igual = usuario == usuario_cadastro
senha_igual = senha == senha_cadastro

print(usuario_igual)
print(senha_igual)

conceder_acesso = usuario_igual & senha_igual
print(conceder_acesso)